<?php 
    include("../includes/layout/header.php");
    head("About");
    include("../includes/search.php");
    include("../includes/easy_login.php");
    include("../includes/logo.php");
    include("../includes/navigation.php");
    include("../includes/layout/footer.php");
?>