<?php
class JConfig {
	public $offline = '0';
	public $offline_message = 'Hyakki\'s Corner is down for maintenance. Please come back later!

- Hyakki &amp; Professor Ragna';
	public $display_offline_message = '1';
	public $offline_image = '';
	public $sitename = 'hyakkiscorner.com';
	public $editor = 'codemirror';
	public $captcha = '0';
	public $list_limit = '20';
	public $access = '1';
	public $dbtype = 'mysql';
	public $host = 'hya1316812541645.db.10386188.hostedresource.com';
	public $user = 'hya1316812541645';
	public $password = 'Hyakkidb21!';
	public $db = 'hya1316812541645';
	public $dbprefix = 'jos_';
	public $secret = 'ef3e111c777ee0672b4475265f25348e';
	public $gzip = '0';
	public $error_reporting = 'default';
	public $helpurl = 'http://help.joomla.org/proxy/index.php?option=com_help&keyref=Help{major}{minor}:{keyref}';
	public $ftp_host = '';
	public $ftp_port = '';
	public $ftp_user = '';
	public $ftp_pass = '';
	public $ftp_root = '';
	public $ftp_enable = '0';
	public $tmp_path = './tmp';
	public $log_path = './logs';
	public $live_site = '';
	public $force_ssl = '0';
	public $offset = 'UTC';
	public $lifetime = '15';
	public $session_handler = 'database';
	public $mailer = 'smtp';
	public $mailfrom = 'air.jourdan21@gmail.com';
	public $fromname = 'hyakkiscorner.com';
	public $sendmail = '/usr/sbin/sendmail';
	public $smtpauth = '0';
	public $smtpuser = '';
	public $smtppass = '';
	public $smtphost = 'relay-hosting.secureserver.net';
	public $caching = '0';
	public $cachetime = '15';
	public $cache_handler = 'file';
	public $debug = '0';
	public $debug_lang = '0';
	public $MetaDesc = 'Hyakki’s Corner was founded in 2013 to provide gamers with quality video game guides and reviews, as well as the opportunity to interact and connect with fellow gamers through not only video games and forums, but also social media.';
	public $MetaKeys = 'hyakki’s corner, games, reviews, guides, forums, video games, video game, video game issues, video game debate, video game debates, video game reviews, video game guides, video game analysis, quality video game reviews, quality video game analysis, quality video game guides, video game forums, video game discussion, video game stream, video game streams, video stream, video game stream, gamer, gamers, video gamer, video gamers, gaming, social media, pc, xbox360';
	public $MetaTitle = '1';
	public $MetaAuthor = '1';
	public $MetaVersion = '0';
	public $robots = '';
	public $sef = '1';
	public $sef_rewrite = '1';
	public $sef_suffix = '0';
	public $unicodeslugs = '0';
	public $feed_limit = '10';
	public $feed_email = 'author';
	public $smtpsecure = 'none';
	public $smtpport = '25';
	public $MetaRights = '';
	public $sitename_pagetitles = '0';
	public $cookie_domain = '';
	public $cookie_path = '';
}